-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(price * sales_amount) AS SALES
FROM PRODUCT AS pr JOIN OFFLINE_SALE AS os
ON pr.PRODUCT_ID = os.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE